---
name: integration-test
releases:
- name: openvpn
  url: file://((repo_dir))
  version: create
update:
  canaries: 2
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 2
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: role1
  azs: [z1]
  jobs:
  - release: openvpn
    name: openvpn
    properties:
      <<: *openvpn
      server: 192.168.202.0 255.255.255.0
      client_config:
        - |
          client
          dev tun
          proto tcp
          remote 0.role2.default.integration-test.bosh 1194
          comp-lzo
          cipher BF-CBC
          keysize 256
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          mute-replay-warnings
          remote-cert-tls server
          verb 3
          mute 20
          tls-client
          <ca>
          ((role1_client.ca))
          </ca>
          <cert>
          ((role1_client.certificate))
          </cert>
          <key>
          ((role1_client.private_key))
          </key>
  instances: 1
  stemcell: default
  vm_type: default
  networks:
  - name: default
- name: role2
  azs: [z1]
  jobs:
  - release: openvpn
    name: openvpn
    properties:
      <<: *openvpn
      server: 192.168.206.0 255.255.255.0
      client_config:
        - |
          client
          dev tun
          proto tcp
          remote 0.role1.default.integration-test.bosh 1194
          comp-lzo
          cipher BF-CBC
          keysize 256
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          mute-replay-warnings
          remote-cert-tls server
          verb 3
          mute 20
          tls-client
          <ca>
          ((role2_client.ca))
          </ca>
          <cert>
          ((role2_client.certificate))
          </cert>
          <key>
          ((role2_client.private_key))
          </key>
  instances: 1
  stemcell: default
  vm_type: default
  networks:
  - name: default
properties:
  openvpn: &openvpn
    ca_crt: ((server_crt.ca))
    server_crt: ((server_crt.certificate))
    server_key: ((server_crt.private_key))
    dh_pem: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
      LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
      2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
      /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
      9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
      fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
      -----END DH PARAMETERS-----
variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: server_crt
  type: certificate
  options:
    ca: ca
    common_name: server
    alternative_names:
    - 0.role1.default.openvpn-deployment.bosh
    - 0.role2.default.openvpn-deployment.bosh
    extended_key_usage:
    - server_auth
- name: role1_client
  type: certificate
  options:
    ca: ca
    common_name: role1
    extended_key_usage:
    - client_auth
- name: role2_client
  type: certificate
  options:
    ca: ca
    common_name: role2
    extended_key_usage:
    - client_auth
