---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/openvpn-bosh-release"
    tag: "ci-bosh-develop"
inputs:
  - name: "blob"
  - name: "repo"
outputs:
  - name: "repo"
    path: "updated-repo"
run:
  path: "repo/ci/tasks/bump-release-blob/run.sh"
params:
  blob: ~
