---
final_name: openvpn
description: |
  A [BOSH](https://bosh.io/) release to help manage an [OpenVPN](https://openvpn.net/index.php/open-source.html) network.
blobstore:
  provider: s3
  options:
    bucket_name: dpb587-bosh-release-openvpn-us-east-1
