---
platform: "linux"
image: "docker:///dpb587/openvpn-bosh-release#bosh-release"
inputs:
  - name: "develop-repo"
  - name: "master-repo"
  - name: "candidate-repo"
  - name: "candidate-release"
  - name: "version"
outputs:
  - name: "master-release-artifacts"
  - name: "master-repo"
    path: "updated-master-repo"
  - name: "develop-repo"
    path: "updated-develop-repo"
run:
  path: "candidate-repo/ci/tasks/finalize-release/run.sh"
params:
  blobstore_s3_access_key_id: ~
  blobstore_s3_secret_access_key: ~
  git_user_email: ~
  git_user_name: ~