---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/openvpn-bosh-release"
    tag: "ci-bosh-develop"
inputs:
  - name: "repo"
  - name: "dev-release"
  - name: "version"
outputs:
  - name: "repo"
    path: "updated-repo"
  - name: "release"
  - name: "github-release"
run:
  path: "repo/ci/tasks/finalize-release/run.sh"
params:
  blobstore_s3_access_key_id: ~
  blobstore_s3_secret_access_key: ~
  git_user_email: ~
  git_user_name: ~
